version: "3"
services:
    #  composer_installation:
    #    container_name: composer_installation
    #    image: composer
    #    volumes:
    #      - ./:/app
    #    command: composer install
    php-apache:
        image: thecodingmachine/php:8.1-v4-apache-node16
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            APACHE_EXTENSION_DAV: 0
            PHP_INI_MEMORY_LIMIT: 1g
            PHP_INI_ERROR_REPORTING: E_ALL
            PHP_EXTENSIONS: pgsql gettext imap sockets zip curl dom gd exif intl mbstring bcmath curl dom opcache mbstring soap xml xmlrpc fileinfo intl xml pdo_sqlite pdo_mysql pdo_pgsql
            PECL_EXTENSION: sodium
            STARTUP_COMMAND_1: composer install
